version: '3.8'

# Extend the base docker-compose file
x-extends:
  file: docker-compose.base.yml
  service: services

# Add additional services specific to this environment
services:
  # Inherit base services
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  
  zookeeper:
    extends:
      file: docker-compose.base.yml
      service: zookeeper
  
  kafka:
    extends:
      file: docker-compose.base.yml
      service: kafka

  # Add backend service
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/grimos
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ALLOWED_ORIGINS=http://localhost:3000
      - SECRET_KEY=dev-secret-key
      - ENVIRONMENT=development
      - DEBUG=true
    depends_on:
      - postgres
      - redis
      - kafka