version: '3.8'

services:
  api-gateway:
    environment:
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ./services/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  frontend:
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm dev

  auth:
    environment:
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./services/auth:/usr/src/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
