global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds

scrape_configs:
  - job_name: 'grimos-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']  # Backend service name and port
        labels:
          app: 'grimos-backend'
          environment: '${ENVIRONMENT:-development}'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Node exporter for machine metrics
        labels:
          app: 'node-exporter'
          environment: '${ENVIRONMENT:-development}'
