[tool.poetry]
name = "shared-utils"
version = "0.1.0"
description = "Shared Python utilities for grimOS backend services"
authors = ["grimOS Team"]

[tool.poetry.dependencies]
python = ">=3.11"
fastapi = "^0.95.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
