version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth:8000
      - JWT_SECRET=${JWT_SECRET}
      - SERVICE_SECRET_KEY=${SERVICE_SECRET_KEY}
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100
      - CORS_ORIGIN=http://localhost:3000,http://localhost:5173
    depends_on:
      - auth
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

  auth:
    build:
      context: ../auth
      dockerfile: Dockerfile
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
      - SECRET_KEY=${SECRET_KEY}
      - SERVICE_SECRET_KEY=${SERVICE_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - ENVIRONMENT=local
      - BACKEND_CORS_ORIGINS=["http://localhost:5000"]
    volumes:
      - ../auth:/app
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  auth-postgres-data:
