apiVersion: apps/v1
kind: Deployment
metadata:
  name: grimos-backend
  labels:
    app: grimos-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: grimos-backend
  template:
    metadata:
      labels:
        app: grimos-backend
    spec:
      containers:
        - name: grimos-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
