apiVersion: v1
kind: Service
metadata:
  name: grimos-backend
  labels:
    app: grimos-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: grimos-backend
