version: '3.8'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"  # FastAPI HTTP
      - "50052:50052"  # gRPC
    environment:
      - ENVIRONMENT=local
      - POSTGRES_SERVER=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
      - AUTH_SERVICE_HOST=auth
      - AUTH_SERVICE_PORT=50051
      - BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://localhost:8000"]
    depends_on:
      - user-db
    networks:
      - grimoire-network

  user-db:
    image: postgres:15
    volumes:
      - user-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    ports:
      - "5433:5432"  # Different port from auth-db
    networks:
      - grimoire-network

volumes:
  user-db-data:

networks:
  grimoire-network:
    external: true