apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: api-gateway
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:
      - name: grimos-backend
        url: http://grimos-backend:8000
        plugins:
          - name: cors
            config:
              origins:
                - '*'
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                - PATCH
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - X-Auth-Token
                - Authorization
              exposed_headers:
                - X-Auth-Token
              credentials: true
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 100
              hour: 1000
              policy: local
              fault_tolerant: true
          - name: prometheus
            config:
              status_code_metrics: true
              latency_metrics: true
              bandwidth_metrics: true
              upstream_health_metrics: true

        routes:
          - name: api-route
            strip_path: false
            paths:
              - /api/v1
          - name: metrics-route
            strip_path: false
            paths:
              - /metrics
          - name: health-route
            strip_path: false
            paths:
              - /health

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:2.8-alpine
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /etc/kong/kong.yml
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
          ports:
            - name: proxy
              containerPort: 8000
            - name: proxy-ssl
              containerPort: 8443
            - name: admin
              containerPort: 8001
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong/kong.yml
              subPath: kong.yml
          readinessProbe:
            httpGet:
              path: /status
              port: admin
            initialDelaySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /status
              port: admin
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: kong-config
          configMap:
            name: kong-config

---
apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: api-gateway
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8001
      targetPort: 8001
  selector:
    app: kong

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  namespace: api-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.grimos.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: kong
                port:
                  number: 8000
