# Values for secret management
secrets:
  enabled: true
  vault:
    enabled: true
    address: "http://vault:8200"
    token: "${VAULT_TOKEN}"

kubernetesSecrets:
  enabled: true
  secrets:
    - name: database-credentials
      data:
        username: "db_user"
        password: "db_password"

databaseUrl: "postgres://user:password@db:5432/grimos"
apiKey: "your-api-key"
