\
# Filepath: /home/brylow/grimOS/charts/grimos-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grimos-service.fullname" . }}
  labels:
    {{- include "grimos-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }} # Ensure this matches the containerPort in deployment.yaml
      protocol: TCP
      name: http
  selector:
    {{- include "grimos-service.selectorLabels" . | nindent 4 }}
